#ifndef GLOBAL_H
#define GLOBAL_H

#define MAXBUFFSIZE 2048
#define NULL_TERMINATOR 1

enum statusCodes {
  SUCCESS, INTERNAL_ERROR, FILE_NOT_FOUND, PARSING_FAILED, METHOD_NOT_ALLOWED
};

#endif // !GLOBAL_H
